language: node_js
node_js:
  - lts/dubnium
  - node
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: 0R62yZRoiwWYyOJu6nFxtRh8WAXIslILpyFhDlWS1RvxK0gqBc+yRFP2sVo+wsiRR2QhWxET7IAG1fNiJmO81iABxI5Xlw2e7X3J8SjJlyM/jxdd1jL6eosG93j0QLCUSCiJLuYFCTlwAIB0J50POk0nEXIRMblRU9Hp8fjg/D1SKVOIx8c0U2C5y8YCaQQqpwQlSRVeYBDB1t/rJy1t7r41qwgh1c0lKeESALCmhXZiHC885yUQTxJClLRJgY1Jz6vv/ENq0jFb/TotMnNQXiOMRWgX2QWGy98/SBAyUyWWPDIHCYBsiQwslbK6CwC+WgXS42PLQqXjsyylN/hTnDYZtqN5icg0zKFw3P4uD0up4ZVDFbY/XWefTH4eWXbLpljBkBslWRrfqPIp+xee+7NpeO+LNwkldu7uBDF9eLVj5NaZHIhNzsGBHrHf+NzdbWANYboitMe0tnYx91GCBoOqQC6Miz9fm2XIfHoKEDN9vtwfRCoiHKTi59hQ1FAPITeeuGb6/TGWz7OoNLm8m2ih3LO4t9vIo5JjotQJEaEHAdeuzZ2RCxRfLmfqMy9uj6Cy6rnagCl456EusTcFCuJv2fqqgJ/qt7HxEiEWAhfwt9BHogELu7iq3l5+30iy9eF16sxTu1EZOK3ISwt+pfeIsxdyyPYrvde2lApEtzY=
  file:
    - 'trim-lines.js'
    - 'trim-lines.min.js'
  on:
    tags: true
